import os

os_env = os.environ

DEBUG = True

DATABASE_NAME = os_env.get('PRODUCT_DATABASE_NAME')
DATABASE_PORT = os_env.get('PRODUCT_DATABASE_PORT')
DATABASE_ADDRESS = os_env.get('PRODUCT_DATABASE_ADDRESS')
DATABASE_USER = os_env.get('PRODUCT_DATABASE_USER')
DATABASE_PASSWORD = os_env.get('PRODUCT_DATABASE_PASSWORD')
DATABASE_DRIVER = os_env.get('PRODUCT_DATABASE_DRIVER')
SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_ADDRESS}/{DATABASE_NAME}'

SECRET_KEY = os.environ['APP_SECRET_KEY']
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
JWT_SECRET_KEY = os.environ['JWT_SECRET_KEY']
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']

