export const FETCH_CUSTOM_QUERY_DATA=  'FETCH_CUSTOM_QUERY_DATA';
export const FETCH_MARKETS = 'FETCH_MARKETS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_PERIODS = 'FETCH_PERIODS';
export const FETCH_FACTS = 'FETCH_FACTS';

export const SET_SELECTED_MARKETS = 'SET_SELECTED_MARKETS';
export const SET_SELECTED_BRANDS = 'SET_SELECTED_BRANDS';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';
export const SET_SELECTED_FACTS = 'SET_SELECTED_FACTS';
export const SET_SELECTED_PERIODS = 'SET_SELECTED_PERIODS';
export const REMOVE_UNSELECTED = 'REMOVE_UNSELECTED';

export const UPLOAD_CSV = "UPLOAD_CSV";
export const EXPORT_CSV = "EXPORT_CSV";
