"""empty message

Revision ID: 068e8b48945d
Revises: 2d1d5b7da04f
Create Date: 2020-02-06 20:58:54.452492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068e8b48945d'
down_revision = '2d1d5b7da04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('johnson_scanner_data', sa.Column('department', sa.String(length=80), nullable=True))
    op.add_column('johnson_scanner_data', sa.Column('retailer', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('johnson_scanner_data', 'retailer')
    op.drop_column('johnson_scanner_data', 'department')
    # ### end Alembic commands ###
