"""empty message

Revision ID: 2d1d5b7da04f
Revises: bdf2dc2180d8
Create Date: 2020-02-06 20:44:03.733276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1d5b7da04f'
down_revision = 'bdf2dc2180d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts_in_johnson_scanner_data', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts_in_johnson_scanner_data', 'value')
    # ### end Alembic commands ###
